USE [master]
GO

/****** Object:  Database [MedSolution]    Script Date: 4/5/2022 4:36:15 PM ******/
CREATE DATABASE [MedSolution]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MedSolution', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MedSolution.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MedSolution_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MedSolution_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MedSolution] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MedSolution].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MedSolution] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MedSolution] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MedSolution] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MedSolution] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MedSolution] SET ARITHABORT OFF 
GO

ALTER DATABASE [MedSolution] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MedSolution] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MedSolution] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MedSolution] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MedSolution] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MedSolution] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MedSolution] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MedSolution] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MedSolution] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MedSolution] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MedSolution] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MedSolution] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MedSolution] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MedSolution] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MedSolution] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MedSolution] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MedSolution] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MedSolution] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MedSolution] SET  MULTI_USER 
GO

ALTER DATABASE [MedSolution] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MedSolution] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MedSolution] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MedSolution] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MedSolution] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MedSolution] SET  READ_WRITE 
GO


